verbose: false
instrumentation:
    root: ./build
    extensions:
        - .js
    default-excludes: true
    excludes: ['**/tests/**']
    compact: true
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
